# Site settings
title: 30-Day Web Development Challenge
email: johnwill.domingo@gmail.com
description: The challenge is to develop simple single-page websites or web projects in thirty days using open source design template resources. Each thirty-day segment has a thematic parameter such as Pure CSS, JavaScript APIs, Parallax, CSS scroll animations, etc. Check out the repo for all the exciting creations!
baseurl: "/webdevchallenge" # the subpath of your site, e.g. /blog/
url: "http://johndomingo.com" # the base hostname & protocol for your site
twitter_username: jwdomingo
github_username:  jwdomingo

# Build settings
markdown: kramdown
permalink: /:title

port: 5000
